### ISSUE TITLE
[Feature request/Proposal] Clustering optimisation techniques in model optimisation techniques

### ISSUE THREAD

**Issue by konstantinARM** [tensorflow/model-optimization#119]
Hi guys,

I was wondering if you have any plans supporting clustering in the Model Optimization Toolkit? By clustering I mean when the weights of different operators are clustered in a way so that only a few unique weights values are used. An example can be found here https://arxiv.org/abs/1510.00149

This can reduce the storage needed for storing different networks and certain types of hardware may benefit from it as well. Clustering can also be combined with pruning and quantization reducing network’s storage requirements even further.

Is this something you see would be useful for this repository? If so, I could look into drafting up an initial pull request so that we could see if this is an acceptable direction early.

What do you think?

Thanks,
Konstantin

P.S. I was trying to understand if this is the right place to post such proposals? The repo main page says to use this link to make feature requests. However, there is no special button for Feature Request hence I opened a regular issue. If that was a wrong way, could you please advise a better communication channel for these matters?

**Comment by akarmi** [comment]
Pull request #125 that implements this optimization technique.

**Comment by alanchiao** [comment]
Thank you @konstantinARM for starting the communication and Anton (@akarmi) for going ahead and creating a pull request! 
Would you both be interested in connecting and meeting to figure how we can move forward with the pull request?

@konstantinARM : with regards to your P.S., the project is early and still needs to establish these communication channels. I've created https://github.com/tensorflow/model-optimization/issues/131 to track this.

**Comment by alanchiao** [comment]
My email is alanchiao@google.com. If you send me an email, I can setup a chat between us and a few others on the Model Optimization project.
We can then bring the results back to this thread and #131 for visibility.

**Comment by alanchiao** [comment]
@akarmi : In literature (blog post or paper), do you know of any that only apply clustering?

**Comment by MohamedNourArm** [comment]
Hi Alan, 

The concept of weight sharing has been mentioned in the literature for a while (since it was quite clear early on that there are redundant weights) but has not been applied explicitly for compression or acceleration before the paper we are using (https://arxiv.org/abs/1510.00149), as part of the optimization pipeline. 

"Soft weight sharing (clustering)" where instead of discrete cluster values, the weights are a multimodal distribution centered around the cluster centroids (but with some little variance around them) has also been referenced in [this early paper](http://www.cs.toronto.edu/~fritz/absps/sunspots.pdf),  but as a means of regularization rather than compression. It was only mentioned much later as a way for compression [here](https://openreview.net/pdf?id=HJGwcKclx), where our paper with the optimization pipeline is also referenced. Another example where clustering is also done (although pre-training) and weight 'buckets' (same as centroids, effectively) are shared is in HashedNets, mentioned [here](https://arxiv.org/pdf/1504.04788.pdf). 

These are, to our knowledge, the only instances of compression using clustering alone (not as part of the pruning/quantization pipeline).

**Comment by akarmi** [comment]
Clustering has been released as part of [TF MOT 0.4.0](https://github.com/tensorflow/model-optimization/releases/tag/v0.4.0).
