### ISSUE TITLE
TEST failures

### ISSUE THREAD

**Issue by psunn** [tensorflow/model-optimization#332]
**Describe the bug**
current on python/core tests, 15 of them are failed

15 failed tests:

1. //tensorflow_model_optimization/python/core/internal/tensor_encoding/core:core_encoder_test
2. //tensorflow_model_optimization/python/core/internal/tensor_encoding/core:encoding_stage_test
3. //tensorflow_model_optimization/python/core/internal/tensor_encoding/core:gather_encoder_test
4. //tensorflow_model_optimization/python/core/internal/tensor_encoding/core:simple_encoder_test
5. //tensorflow_model_optimization/python/core/internal/tensor_encoding/encoders:common_encoders_test
6. //tensorflow_model_optimization/python/core/internal/tensor_encoding/stages:stages_impl_test
7. //tensorflow_model_optimization/python/core/internal/tensor_encoding/stages/research:clipping_test
8. //tensorflow_model_optimization/python/core/internal/tensor_encoding/stages/research:kashin_test
9. //tensorflow_model_optimization/python/core/internal/tensor_encoding/stages/research:misc_test
10. //tensorflow_model_optimization/python/core/internal/tensor_encoding/stages/research:quantization_test
11. //tensorflow_model_optimization/python/core/internal/tensor_encoding/testing:test_utils_test
12. //tensorflow_model_optimization/python/core/internal/tensor_encoding/utils:py_utils_test
13. //tensorflow_model_optimization/python/core/quantization/keras:quantize_test
14. //tensorflow_model_optimization/python/core/sparsity/keras:prune_integration_test
15. //tensorflow_model_optimization/python/core/quantization/keras:quantize_functional_test

I'm wondering is it expected? Any plan to look into them? Thanks

**System information**

TensorFlow installed from (source or binary): source

TensorFlow version: 2.1.0

TensorFlow Model Optimization version:
_(current HEAD)_
commit 08dbdc43871e5e7cb6638ba96e1ad3bfec5837aa (HEAD -> master, origin/master, origin/HEAD)

Python version: 3.6.9

**Describe the expected behavior**
TESTs in python/core should all pass

**Describe the current behavior**
15 of the TESTs are failed now
**Code to reproduce the issue**

Provide a reproducible code that is the bare minimum necessary to generate the
problem.
`
bazelisk test --test_summary=detailed --test_output=all //tensorflow_model_optimization/python/core/...
`

**Comment by akarmi** [comment]
@alanchiao, we have been getting test failures in MOT for a couple of days, is it expected?

**Comment by alanchiao** [comment]
@PraChetit for visibility on tensor encoding ones.

Generally there should not be test issues. The main issue is that we don't have CI testing right now to ensure the techniques work with the relevant TF versions that they should support (e.g. pruning: 1.14.0+, 2.0.0+ and quantization: nightly).

It's in the backlog amongst things I have to do for QAT, Official Models, and others.

Currently the plan is to use TravisCI so that anyone can configure it. It's what many Python-first projects such as numpy, pandas, and ones in the TF ecosystem use and I've gotten the impression that it's easier to work with given our minimal needs, as opposed to Jenkins.

**Comment by psunn** [comment]
TESTs pass now, thanks.
