### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'compile'

### ISSUE THREAD

**Issue by zhoujungis** [tensorflow/model-optimization#37]
when I use prune_model.compile, raise the error

**Comment by johnwang416** [comment]
hello, have you solved this problem yet?

**Comment by johnwang416** [comment]
> when I use prune_model.compile, raise the error

hello, have you solved this problem yet?

**Comment by alanchiao** [comment]
Hi ZhouJun,

You'll need to provide more details (e.g. your code to reproduce this issue). This is not typical and it may be how you're using the pruning API.

**Comment by alanchiao** [comment]
Could you fill this template? This is the template going forward for bugs. It's hard to provide you a solution with the currently available information.

**Describe the bug**
A clear and concise description of what the bug is.

**System information**
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- TensorFlow Model Optimization version:
- Python version:

**Describe the expected behavior**

**Describe the current behavior**

**Code to reproduce the issue**
Provide a reproducible code that is the bare minimum necessary to generate the problem.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by mra75x** [comment]
I think the problem here is that you defined a function with name "prune_model" and you write it as below:
`def prune_model:
      model.add()
      .......................`
and after that you want to compile it by using:
`prune_model.compile(....)`
if this was the case. the error raising maybe is because you didn't return the model after defining the 'prune_model'  function!

`def prune_model:
      model.add()
      .......................
      return model`
