### ISSUE TITLE
Magnitude-based weight pruning with Keras doesn't work with actual Keras models

### ISSUE THREAD

**Issue by lucgiffon** [tensorflow/model-optimization#393]
Hello

The magnitude weight pruning procedure doesn't work with keras layers but only with tf.keras layers. I think it should be stated more clearly in the documentation.

On this page: https://www.tensorflow.org/model_optimization/guide/pruning/pruning_with_keras#build_a_pruned_model_layer_by_layer, I don't think it is specified a single time. I mean in the text. The code actually uses tf.keras but it is unclear why it couldn't work with keras alone. The title should at least be

Magnitude-based weight pruning with tf.keras

And I believe adding a bulletpoint in the "worth clarifying" section would be useful.
 
Bye

**Comment by alanchiao** [comment]
@lucgiffon: thanks for the feedback and welcome followup on my response below. 

I knew about this potential confusion and had something to partially improve it, now submitted [here](https://github.com/tensorflow/model-optimization/blob/master/tensorflow_model_optimization/g3doc/guide/pruning/pruning_with_keras.ipynb), where tf.keras is explicitly mentioned at the start. The API docs [here](https://www.tensorflow.org/model_optimization/api_docs/python/tfmot/sparsity/keras/prune_low_magnitude) take a similar approach. 

It does not go as far as you said though, with mentioning tf.keras in the title and having a "worth clarifying" note, partially because the implicit idea behind anything under tensorflow.org is that it's specific to the TensorFlow version. I agree it's not perfect for everyone, but keeping it as is keeps things concise. 

Past the Keras 2.3.0 release, TF will be the only backend in the official release. See https://github.com/keras-team/keras/releases/tag/2.3.0 and the general documentation updates on keras.io.

**Comment by alanchiao** [comment]
Closing but feel free to reopen.
