### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow_model_optimization'

### ISSUE THREAD

**Issue by zmlim** [tensorflow/model-optimization#425]
My tensorflow version is 1.15.0
when i try to import the module, it gives me the error: ModuleNotFoundError: No module named 'tensorflow_model_optimization'

**Comment by alanchiao** [comment]
`tensorflow_model_optimization` is a a separate python package from tensorflow.

See https://www.tensorflow.org/model_optimization/guide/install for installation instructions.

**Comment by seshuamrita** [comment]
> `tensorflow_model_optimization` is a separate python package from `tensorflow`.
> 
> See https://www.tensorflow.org/model_optimization/guide/install for installation instructions.

after installing also same error occurs , what to do now

**Comment by alejandroariaszuluaga** [comment]
Hello, I'm having the same issue, a simple `pip install -q tensorflow-model-optimization` on Colab worked for me, but on my local environment it doesn't seem to solve the issue, followed the detailed instructions on the link above. Maybe it's because I don't have a GPU available?

Appreciate any help!

**Comment by jleape** [comment]
Same issue here

**Comment by noamgot** [comment]
+ Same here
@nutsiepully please consider re-opening this issue...
