### ISSUE TITLE
QAT for MultiHeadAttention

### ISSUE THREAD

**Issue by wwwind** [tensorflow/model-optimization#718]
**System information**

- TensorFlow version (you are using): nightly
- Are you willing to contribute it (Yes/No): Yes

**Motivation**

We would like to run QAT for transformer models.

**Describe the feature**
It will be good to have a support of MultiHeadAttention layer for QAT.

**Describe how existing APIs don't satisfy your use case (optional if obvious)**

This is the small model that fails currently:

`
import tensorflow as tf
import numpy as np

input = tf.keras.layers.Input(shape=(32, 32), batch_size=100)
x = tf.keras.layers.MultiHeadAttention(num_heads=2, key_dim=16)(input, input)

out = tf.keras.layers.Flatten()(x)

model = tf.keras.Model(inputs=input, outputs=out)
`

**Comment by xhae** [comment]
@Xhark , can you take a look on this?

**Comment by Xhark** [comment]
Internally it contains multiple einsum_dense layers which we don't support yet.
I'm working on applying QAT for Transformer based models like BERT, but I realize it's not trivial to support MultiHeadAttention layer. because:

 - It has multiple inputs.
 - Due to we don't have QuantizedMultiHeadAttentionOp for TFLite, we usually convert it to multiple Dense ops. In that case, we have to add multiple quantization point, which we don't supports yet.

 The easiest work around I'm going to try first is add MultiHeadAttentionQuantized layer and add transform rule for it. It seems works for some case, but need to spend more time to make sure it can be supports most of case wide enough. I'm going to add update if I make some progress. Thanks.

**Comment by wwwind** [comment]
Hi @Xhark Sorry to bother, but I would like to check the status of this issue. Is it still in development or is it postponed due to issues ? Thanks!

**Comment by dlmacedo** [comment]
Any news regarding this?

**Comment by hbellafkir** [comment]
Any update on this @Xhark ?
