### ISSUE TITLE
How to quant InputLayer by  AllValuesQuantizer  manually？

### ISSUE THREAD

**Issue by jiuzhuanzhuan** [tensorflow/model-optimization#768]
Hi,
  After train my quant aware model on tf1.12, i want inference it on tf2.4 by recreate the model use kears.
 Except InputLayer, others have be rebuild by my weight and bias trained on tf1.12. 

 I want quantize input scalemanually, but the code below don't work.
```python
import tensorflow_model_optimization as tfmot
AllValuesQuantizer = tfmot.quantization.keras.quantizers.AllValuesQuantizer
input_layer = keras.layers.InputLayer(input_shape=(256, 256, 3))
quant = AllValuesQuantizer(num_bits=8, per_axis=False, symmetric=True, narrow_range=True)
inputs = quant(input_layer)
```
```bash 
TypeError: __call__() missing 2 required positional arguments: 'training' and 'weights'
```

**Comment by Xhark** [comment]
Instead of use quantizer directly, it might be better to apply quantize_model and then copy the quantizer weights like ~_min / ~_max by model.set_weights().
You may have to use custom quantize_config if some quantization location is different than default one.

Use quantizer directly is the last way for a part of model that uses non-keras ops. (quantize_model/quantize_config QAT API only supports keras layer.)

**Comment by jiuzhuanzhuan** [comment]
Thank u for your kindly reply， that work！
